data:extend({
    {
        type = "item",
        name = "enhanced-combinator-1",
        icon = "__enhanced-combinators__/graphics/icons/enhanced-combinator-1.png",
        icon_size = 32,
        flags = { "goes-to-quickbar" },
        subgroup = "circuit-network",
        place_result = "enhanced-combinator-1",
        order = "c[combinators]-d[enhanced-combinator-1]",
        stack_size = 50
    },
    {
        type = "item",
        name = "enhanced-combinator-2",
        icon = "__enhanced-combinators__/graphics/icons/enhanced-combinator-2.png",
        icon_size = 32,
        flags = { "goes-to-quickbar" },
        subgroup = "circuit-network",
        place_result = "enhanced-combinator-2",
        order = "c[combinators]-d[enhanced-combinator-2]",
        stack_size = 50
    },
    {
        type = "item",
        name = "enhanced-combinator-3",
        icon = "__enhanced-combinators__/graphics/icons/enhanced-combinator-3.png",
        icon_size = 32,
        flags = { "goes-to-quickbar" },
        subgroup = "circuit-network",
        place_result = "enhanced-combinator-3",
        order = "c[combinators]-d[enhanced-combinator-3]",
        stack_size = 50
    },
    {
        type = "item",
        name = "enhanced-output-combinator-1",
        icon = "__enhanced-combinators__/graphics/icons/enhanced-combinator-1.png",
        icon_size = 32,
        flags = { "goes-to-quickbar" },
        subgroup = "circuit-network",
        place_result="enhanced-output-combinator-1",
        order = "c[combinators]-c[enhanced-output-combinator-1]",
        stack_size= 50,
    },
    {
        type = "item",
        name = "enhanced-output-combinator-2",
        icon = "__enhanced-combinators__/graphics/icons/enhanced-combinator-2.png",
        icon_size = 32,
        flags = { "goes-to-quickbar" },
        subgroup = "circuit-network",
        place_result="enhanced-output-combinator-2",
        order = "c[combinators]-c[enhanced-output-combinator-2]",
        stack_size= 50,
    },
    {
        type = "item",
        name = "enhanced-output-combinator-3",
        icon = "__enhanced-combinators__/graphics/icons/enhanced-combinator-3.png",
        icon_size = 32,
        flags = { "goes-to-quickbar" },
        subgroup = "circuit-network",
        place_result="enhanced-output-combinator-3",
        order = "c[combinators]-c[enhanced-output-combinator-3]",
        stack_size= 50,
    },
})